source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EXTView_Example', :exclusive => true do
  pod "EXTView", :path => "../"
end

target 'EXTView_Tests', :exclusive => true do
  pod "EXTView", :path => "../"

  pod 'FBSnapshotTestCase'
end
